# Generated by Django 5.0.3 on 2024-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_description_alter_productreview_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_discounted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
