# Generated by Django 5.0.3 on 2024-07-09 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_customer_name_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(help_text='The shipping ìnformation of the order', on_delete=django.db.models.deletion.CASCADE, related_name='address_fk', to='core.customeraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(help_text='The status of the order', on_delete=django.db.models.deletion.CASCADE, related_name='status_fk', to='core.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='The user of the order', on_delete=django.db.models.deletion.CASCADE, related_name='user_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
